---
title: "Week 5 exercises"
author: "Wing-Ho Ko"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading packages


## Exercise 1: k-means clustering with Penguins

Consider the penguins dataset. 

1. Focus on the four numerical variables bill length, bill depth, flipper length, and body mass. Drop any observations that have NA's in any of those four variables. Rescale the variables so that each has unit variance (hint: you may find the `scale()` function useful for such purpose)

2. Make scatter plots on the results of k-means clustering for k = 2 and k = 3. Use color to distinguish between different cluster generated by the k-means algorithm and use marker shape to distinguish between different penguin species. Make 2 plots for each case so that all numerical variables can be visualized

3. Produce the silhouette plots on the results of k-means clustering for k=2 and k=3 

4. Check the within-cluster-sum-of-squares score and silhouette score to determine how many clusters the data naturally fall into. Does the answer make sense given what you know about the dataset?


## Exercise 2: simple linear regression on penguins

Consider the penguins dataset. Treat body mass as the response variable and flipper length as the explanatory variable.

1. Subset the penguins dataset to retain only the body mass and flipper length variables, and drop any observations that contain `NA`'s

2. Make a plot of body mass versus flipper length. Use `geom_smooth()` to also add the linear regression line

3. Perform the linear regression. How much does body mass increases per unit increase in flipper length? Also determine if the dependence of body mass on flipper length is statistically significant (= discernible)

4. What is the 95% confidence interval in the slope you find in the previous part?

5. Suppose the flipper length of a penguin is measured to be 204 mm. What is the expected body mass of the penguin? And what is the range of body mass you'd expect to cover the body mass of the penguin 90% of the times?

6. Plot the residuals against the explanatory variable. Is there an overall trend in the mean? Is there heteroscedasticity? Also check normality.
